scaleout: 10
cores-per-worker: 1
mem-per-worker: "15GB"
disk-per-worker: "1GB"
queue: "workday"
walltime: "12:00:00"
chunksize: 100000
local-virtualenv: true
# jobs-dir: "test"


# custom-setup-commands:
#   - source ~/PocketCoffea/pocket_coffea_env/bin/activate
#   - export PYTHONPATH=/afs/cern.ch/user/m/mmalucch/PocketCoffea:$PYTHONPATH
